const express = require('express');
const router = express.Router();
const cityController = require('../controllers/cityController');
router.get('/', cityController.getAllCities);
router.get('/favorites', cityController.getFavorites);
router.get('/popular', cityController.getPopularCities);
router.get('/:name', cityController.getCity);
router.post('/', cityController.createCity);
router.put('/:id', cityController.updateCity);
router.delete('/:id', cityController.deleteCity);
module.exports = router;
